version: '3.6'

services:
  rabbitmq:
    build:
        context: rabbitmq/  
    environment:
      RABBITMQ_DEFAULT_USER: cctadmin
      RABBITMQ_DEFAULT_PASS: Three2kill 
    ports:
      - 15672:15672
      - 5672:5672 
    networks: 
      - elk

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/var/log/mongodb
    ports:
      - 27017:27017
    networks: 
      - elk

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xmx512m -Xms256m
      RABBITMQ_USERNAME: cctadmin
      RABBITMQ_PASSWORD: Three2kill
    networks:
      - elk
    depends_on:
      - kibana
      - rabbitmq 

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
